version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: visitor-platform-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: visitor
      POSTGRES_PASSWORD: visitor_pass
      POSTGRES_DB: visitor_platform
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: