import {
  Box,
  Columns,
  Code2,
  CreditCard,
  MousePointerClick,
  FileText,
  Gift,
  Handshake,
  LayoutGrid,
  Layers,
  Mail,
  Menu,
  Sparkles,
  Star,
  TerminalSquare,
  TrendingUp,
  UserPlus,
  Zap,
  Clock,
} from 'lucide-react';

export const BLOCK_ICONS = {
  section: LayoutGrid,
  container: Box,
  row: Columns,
  column: Layers,
  hero: Sparkles,
  navbar: Menu,
  text: FileText,
  image: Mail,
  countdown: Clock,
  cta: MousePointerClick,
  testimonials: Star,
  checkout: CreditCard,
  order_bump: Gift,
  upsell: TrendingUp,
  affiliate: Handshake,
  affiliate_signup: UserPlus,
  referral_dashboard: Zap,
  customer_login: UserPlus,
  html: Code2,
  script: TerminalSquare,
};
